<?php

use Faker\Generator as Faker;

$factory->define(\App\Role::class, function (Faker $faker) {
    return [
        'id' => $faker->lexify('factoryGeneratedRole:?????????????'),
        'name' => 'Role (Generated by a factory)',
        'description' => 'Dit is een role die door een factory is gegenereerd. Alleen voor test-toepassingen deze role gebruiken!',
        'is_required' => false,
        'is_visible' => false
    ];
});
